export const ACTION_FILM_LIST_FETCH_REQUEST = 'ACTION_FILM_LIST_FETCH_REQUEST'

export const ACTION_FILM_LIST_FETCH_SUCCESS = 'ACTION_FILM_LIST_FETCH_SUCCESS'

export const ACTION_FILM_LIST_FETCH_FAIL = 'ACTION_FILM_LIST_FETCH_FAIL'