export const ACTION_FILM_LIST_FETCH_REQUEST = 'ACTION_FILM_LIST_FETCH_REQUEST'

export const ACTION_FILM_LIST_FETCH_SUCCESS = 'ACTION_FILM_LIST_FETCH_SUCCESS'

export const ACTION_FILM_LIST_FETCH_FAIL = 'ACTION_FILM_LIST_FETCH_FAIL'

export const ACTION_FILM_FETCH_REQUEST = 'ACTION_FILM_FETCH_REQUEST'

export const ACTION_FILM_FETCH_SUCCESS = 'ACTION_FILM_FETCH_SUCCESS'

export const ACTION_FILM_FETCH_FAIL = 'ACTION_FILM_FETCH_FAIL'

export const ACTION_CHARACTER_LIST_FETCH_REQUEST = 'ACTION_CHARACTER_LIST_FETCH_REQUEST'

export const ACTION_CHARACTER_LIST_FETCH_SUCCESS = 'ACTION_CHARACTER_LIST_FETCH_SUCCESS'

export const ACTION_CHARACTER_LIST_FETCH_FAIL = 'ACTION_CHARACTER_LIST_FETCH_FAIL'

export const ACTION_CHARACTER_FETCH_REQUEST = 'ACTION_CHARACTER_FETCH_REQUEST'

export const ACTION_CHARACTER_FETCH_SUCCESS = 'ACTION_CHARACTER_FETCH_SUCCESS'

export const ACTION_CHARACTER_FETCH_FAIL = 'ACTION_CHARACTER_FETCH_FAIL'

export const ACTION_PLANET_FETCH_REQUEST = 'ACTION_PLANET_FETCH_REQUEST'

export const ACTION_PLANET_FETCH_SUCCESS = 'ACTION_PLANET_FETCH_SUCCESS'

export const ACTION_PLANET_FETCH_FAIL = 'ACTION_PLANET_FETCH_FAIL'